disabled: false

builders:
    - docker
docker_name: nav-container

extra_jobs:
    - name: nav-container-carbon-cache
      builders:
          - docker
      docker_name: nav-container/carbon-cache
      docker_context_dir: carbon-cache
    - name: nav-container-graphite-web
      builders:
          - docker
      docker_name: nav-container/graphite-web
      docker_context_dir: graphite-web
