version: '2'
services:
  nav:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./data/log:/usr/local/nav/var/log
      - ./data/roomimages:/usr/local/nav/var/uploads/images/rooms
    depends_on:
      - postgres
      - carbon-cache
      - graphite-web
    environment:
      - PGHOST=postgres
      - PGDATABASE=nav
      - PGUSER=nav
      - PGPORT=5432
      - CARBONHOST=carbon-cache
      - CARBONPORT=2003
      - GRAPHITEWEB=http://graphite-web/
      - NOINITDB=0
    env_file:
      - nav-variables.env

  postgres:
    image: "postgres:9.4"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  carbon-cache:
    build: ./carbon-cache
    volumes_from:
      - whisper

  graphite-web:
    build: ./graphite-web
    # We don't really want this to be public, since there is no authentication
    # ports:
    #   - "8000:80"
    environment:
      - TIME_ZONE=Europe/Oslo
      - CARBONLINK_HOSTS=carbon-cache:7002
    volumes_from:
      - whisper

  whisper:
    image: busybox
    volumes:
      - ./data/whisper:/var/lib/graphite/storage/whisper
